### ISSUE TITLE
Timeout problem

### ISSUE THREAD

**Issue by Mac1q** [urielha/log4stash#17]
Hello,
I have this problem during logging:
```
log4net:ERROR Invalid connection to ElasticSearch
System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at log4stash.WebElasticClient.SendRequest(WebRequest webRequest, String requestString) in d:\uriel\Programing\C#\log4stash\src\log4stash\ElasticClient\ElasticClient.cs:line 152
   at log4stash.WebElasticClient.PrepareBulkAndSend(IEnumerable`1 bulk) in d:\uriel\Programing\C#\log4stash\src\log4stash\ElasticClient\ElasticClient.cs:line 129
   at log4stash.WebElasticClient.IndexBulk(IEnumerable`1 bulk) in d:\uriel\Programing\C#\log4stash\src\log4stash\ElasticClient\ElasticClient.cs:line 98
   at log4stash.ElasticSearchAppender.DoIndexNow() in d:\uriel\Programing\C#\log4stash\src\log4stash\ElasticSearchAppender.cs:line 175
```

I tried update for last 2.0.2-c but same issue, only line numbers changed:
```
log4net:ERROR Invalid request to ElasticSearch
System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at log4stash.WebElasticClient.SafeSendRequest(RequestDetails request, Func`1 getRequestStream) in d:\uriel\Programing\C#\log4stash\src\log4stash\ElasticClient\ElasticClient.cs:line 169
```
Could you please help?

**Comment by Mac1q** [comment]
And connection is OK, I tried it via Sense API and for 4-5days I logged without problem

**Comment by urielha** [comment]
Do you have any firewall on the way?
I haven't encounter such problem before, what environment are you using?

**Comment by urielha** [comment]
Closed due to inactivity. If this happened again please reopen.
